### ISSUE TITLE
customer action

### ISSUE THREAD

**Issue by wdqzdd** [dtm-labs/client-csharp#70]
![image](https://github.com/dtm-labs/client-csharp/assets/27991992/5cebe7dd-7e08-44ce-a6da-f88a55e1d245)
如果这里只是指定的url。可能会很局限。
比如说：
1、我们系统url调用即使错误业务返回统一格式的数据。即使失败也不会http异常
2、我可能不是一个http调用。只是本地d代码处理了一些业务逻辑。
3、正向调用返回的数据可能会在逆向调用中使用。
4、第一个saga.Add返回的数据可能会给第二个saga.Add使用

**Comment by wdqzdd** [comment]
![image](https://github.com/dtm-labs/client-csharp/assets/27991992/f18c29f1-63ba-4d9f-933c-451ec9f9469a)

**Comment by catcherwong** [comment]
你说的这种场景，可能用 dtm 的 workflow模式会更合适

https://dtm.pub/practice/workflow.html

**Comment by wooln** [comment]
> 3、正向调用返回的数据可能会在逆向调用中使用。
> 4、第一个saga.Add返回的数据可能会给第二个saga.Add使用

针对3、4的场景作者在文档中有解释为什么没提供和若真需要的解决方案 [SAGA事务模式 #更多高级场景-其他分支的结果作为输入 | DTM开源项目文档](https://dtm.pub/practice/saga.html#%E5%85%B6%E4%BB%96%E5%88%86%E6%94%AF%E7%9A%84%E7%BB%93%E6%9E%9C%E4%BD%9C%E4%B8%BA%E8%BE%93%E5%85%A5)
