### ISSUE TITLE
how to implement sub barrier transaction for this case, can you implement more?

### ISSUE THREAD

**Issue by khabt** [dtm-labs/client-csharp#73]
how to implement for example in c#, can you implement more?

![image](https://github.com/dtm-labs/client-csharp/assets/34017893/c3647b77-87ec-4b16-8b5a-1e944d3f84ba)

**Comment by catcherwong** [comment]
@khabt Thanks for your interest in this project.

Do you mean how to write code in `branchBarrier.Call`?

Here is a sample that you can follow: 

https://github.com/dtm-labs/client-csharp/blob/c86f875882891f278f1a78b046de33d0065b15cf/tests/BusiGrpcService/Services/BusiApiService.cs#L217

**Comment by khabt** [comment]
Yeah, my project is using DTM to implement distribution transactions. 
Thank you for your simple code.
