### ISSUE TITLE
在SAGA模式下，接口请求超过一直重试

### ISSUE THREAD

**Issue by light714** [dtm-labs/client-csharp#78]
在SAGA模式下，接口一旦大于3秒，就会超时，每次重试也是超过3秒，会一直重试，这种情况该如何处理呢？

**Comment by catcherwong** [comment]
接口是 DTM server 的接口还是分支事务的接口？

要避免一直重试，可以设置最大重试次数和事务结束时间。

**Comment by catcherwong** [comment]
关于3秒的问题，是 DTM server 默认有一个执行超时时间，这个时间可以从客户端传递，C# 客户端预计这周会添加支持。

如果你这边有时间，也可以尝试调整一下。

参考
https://github.com/dtm-labs/dtm/blob/main/client/dtmcli/dtmimp/trans_base.go#L48

**Comment by light714** [comment]
是分支事务，因为分支事务会超过3秒，那支持后是否会发布新的版本

**Comment by light714** [comment]
我已经修改完成，但是不知道怎么提交，是不是并没有权限提交

**Comment by catcherwong** [comment]
先Fork，然后改代码，改完代码提交，然后 PR

**Comment by catcherwong** [comment]
`1.5.0-alpha20240514080351` 包含了这个提交
